/**
 * Vendor the Chart.js UMD (auto-registering, minified) build into a TS module as
 * a string constant, so it can be inlined into the sandboxed HTML-answer iframe
 * at render time (see src/lib/html.ts). Inlining keeps the sandbox locked
 * (`default-src 'none'`, no network) while still giving model-authored HTML a
 * real charting library — no CDN dependency, renders offline.
 *
 * Re-run after bumping the chart.js dependency:  node scripts/vendor-chartjs.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const src = readFileSync(
  join(root, "node_modules/chart.js/dist/chart.umd.min.js"),
  "utf8",
);

// Pull the version out of the banner for a breadcrumb in the generated file.
const versionMatch = src.match(/Chart\.js v([\d.]+)/);
if (!versionMatch) {
  console.warn(
    "vendor-chartjs: could not parse version from the chart.js banner — writing 'unknown'.",
  );
}
const version = versionMatch?.[1] ?? "unknown";

const out = `// @generated by scripts/vendor-chartjs.mjs — DO NOT EDIT BY HAND.
// Chart.js v${version} (UMD, auto-registering, minified). MIT License.
// Inlined into the sandboxed HTML-answer iframe so charts work with zero network.
/* eslint-disable */
export const CHARTJS_VERSION = ${JSON.stringify(version)};
export const CHARTJS_SOURCE = ${JSON.stringify(src)};
`;

const dest = join(root, "src/lib/vendor/chartjs.generated.ts");
writeFileSync(dest, out);
console.log(
  `Wrote ${dest} — Chart.js v${version}, ${(src.length / 1024).toFixed(0)}KB source.`,
);
